# Generated by Django 4.2.7 on 2023-11-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identidad', models.CharField(max_length=20, unique=True)),
                ('cod_carrera', models.CharField(max_length=5)),
                ('correo_personal', models.CharField(max_length=100)),
                ('cod_centro', models.CharField(max_length=5)),
                ('correo_institucional', models.CharField(max_length=100)),
                ('num_cuenta', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
