# Generated by Django 4.2.7 on 2023-11-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0002_rename_nombre_carrera_nombre_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identidad', models.CharField(max_length=20, unique=True)),
                ('correo_personal', models.CharField(max_length=100)),
                ('num_cuenta', models.CharField(default='', max_length=100, unique=True)),
                ('correo_institucional', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('indice_global', models.IntegerField(default=0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_estudiante', to='registro.carrera')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_estudiante', to='registro.centroregional')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_estudiante', to='estudiante.estudiante', to_field='num_cuenta')),
                ('tipoSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_solicitud', to='estudiante.tiposolicitud')),
            ],
        ),
    ]
