# Generated by Django 4.2.7 on 2023-11-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_nombre_carrera_nombre_carrera_and_more'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cod_carrera',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='cod_centro',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='carrera_estudiante', to='registro.carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='centro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='centro_estudiante', to='registro.centroregional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='indice_global',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo_institucional',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='num_cuenta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
