# Generated by Django 4.2.7 on 2023-11-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_tiposolicitud_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estudiante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_estudiante', to='estudiante.estudiante'),
            preserve_default=False,
        ),
    ]
