# Generated by Django 4.2.7 on 2023-11-27 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_solicitud_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='num_cuenta',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_estudiante', to='estudiante.estudiante', to_field='num_cuenta'),
        ),
    ]
