# Generated by Django 4.2.7 on 2023-11-14 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0002_rename_nombre_carrera_nombre_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_personal', models.CharField(max_length=100)),
                ('cod_carrera1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_principal', to='registro.carrera')),
                ('cod_carrera2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_secundaria', to='registro.carrera')),
                ('cod_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admision_cod_centro', to='registro.centroregional')),
            ],
        ),
    ]
