# Generated by Django 4.2.7 on 2023-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=20)),
                ('tipo_examen', models.CharField(max_length=10)),
                ('nota', models.IntegerField()),
            ],
        ),
    ]
