# Generated by Django 4.2.7 on 2023-11-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_nombre_carrera_nombre_carrera_and_more'),
        ('admisiones', '0002_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_id', to='admisiones.admision'),
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(max_length=10)),
                ('nota', models.IntegerField()),
                ('cod_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cod_carrera_req', to='registro.carrera')),
            ],
        ),
    ]
