# Generated by Django 4.2.7 on 2023-11-20 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0003_alter_calificacion_identidad_requerimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_id', to='admisiones.admision', to_field='identidad'),
        ),
    ]
